### ISSUE TITLE
Update 1.8.16 > 1.8.23 No module named 'numpy'

### ISSUE THREAD

**Issue by Constuelo** [psd-tools/psd-tools#125]
After updating I get the following error from psd_tools\composer\blend.py

OS: Windows 10

Traceback error
```
$ C:/Users/rory.ferguson/AppData/Local/Programs/Python/Python37-32/python.exe "x:/WebDesign/AW19/emails/z_
approved/test/New folder/main.py"
Traceback (most recent call last):
  File "x:/WebDesign/AW19/emails/z_approved/test/New folder/main.py", line 7, in <module>
    image = layer.compose()
  File "C:\Users\rory.ferguson\AppData\Local\Programs\Python\Python37-32\lib\site-packages\psd_tools\api\layers.py", line 510, in compose
    return compose(self, **kwargs)
  File "C:\Users\rory.ferguson\AppData\Local\Programs\Python\Python37-32\lib\site-packages\psd_tools\composer\__init__.py", line 130, in compose
    image = compose_layer(layer, **kwargs)
  File "C:\Users\rory.ferguson\AppData\Local\Programs\Python\Python37-32\lib\site-packages\psd_tools\composer\__init__.py", line 188, in compose_layer
    layer.clip_layers, bbox=bbox, context=image.copy()
  File "C:\Users\rory.ferguson\AppData\Local\Programs\Python\Python37-32\lib\site-packages\psd_tools\composer\__init__.py", line 138, in compose
    context = blend(context, image, offset, layer.blend_mode)
  File "C:\Users\rory.ferguson\AppData\Local\Programs\Python\Python37-32\lib\site-packages\psd_tools\composer\blend.py", line 48, in blend
    image = _blend_image(backdrop, image, blend_func)
  File "C:\Users\rory.ferguson\AppData\Local\Programs\Python\Python37-32\lib\site-packages\psd_tools\composer\blend.py", line 58, in _blend_image
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
```

**Comment by Constuelo** [comment]
This happened when updating `pip install -U psd-tools` and `pip install psd-tools`

Obviously `pip install numpy` fixes the issue

**Comment by kyamagu** [comment]
@Constuelo Thanks for reporting this. As you might have noticed, numpy/scipy is required when full composer functionality is needed. See documentation:

https://psd-tools.readthedocs.io/en/latest/#installation
