### ISSUE TITLE
Error saving individual layer as png file AttributeError: 'Image' object has no attribute 'getchannel'

### ISSUE THREAD

**Issue by change2014** [psd-tools/psd-tools#143]
I am trying to save each layer as individual png file. Below is code. 
k = 0 
for layer in psd:
    name = str(k)+".png"
    path = '/Users/shivang.s/Documents/autoContent/DataSets/photoshopData/banner3/elements/' + name
    layer.compose().save(path)
    k = k +1   

Some layers are getting saved while some are throwing below error. Please help. 

  File "<ipython-input-18-f149ad7b72f8>", line 6, in <module>
    layer.compose().save(path)

  File "/Users/shivang.s/anaconda/lib/python3.6/site-packages/psd_tools/api/layers.py", line 379, in compose
    return compose_layer(self, **kwargs)

  File "/Users/shivang.s/anaconda/lib/python3.6/site-packages/psd_tools/composer/__init__.py", line 163, in compose_layer
    return _apply_layer_ops(layer, image, force=force, **kwargs)

  File "/Users/shivang.s/anaconda/lib/python3.6/site-packages/psd_tools/composer/__init__.py", line 183, in _apply_layer_ops
    image = apply_mask(layer, image, bbox=bbox)

  File "/Users/shivang.s/anaconda/lib/python3.6/site-packages/psd_tools/composer/__init__.py", line 283, in apply_mask
    mask = ImageChops.darker(image_.getchannel('A'), mask)

AttributeError: 'Image' object has no attribute 'getchannel'

**Comment by kyamagu** [comment]
@change2014 can you share an example?

**Comment by change2014** [comment]
[1312*704.psd.zip](https://github.com/psd-tools/psd-tools/files/3599615/1312.704.psd.zip)

**Comment by change2014** [comment]
i recently installed this package using pip install psd-tools 
this should install latest version right?

**Comment by change2014** [comment]
> ```python
> image.save('%s.png' % layer.name)
> ```

**Comment by change2014** [comment]
> Not all the layers have a visible image. You should check if `compose()` returns a valid image.
> 
> ```python
> for layer in psd:
>     image = layer.compose()
>     if image:
>         image.save('%s.png' % layer.name)
> ```

i did and new code is 
for layer in psd:
    name = str(k)+".png"
    path = '/Users/shivang.s/Documents/autoContent/DataSets/photoshopData/banner3/elements/' + name
    img = layer.compose()
    if img:
        img.save(path)
    k = k +1   
but it is still throwing the same error. 
Traceback (most recent call last):

  File "<ipython-input-33-fa8efe1f62de>", line 6, in <module>
    img = layer.compose()

  File "/Users/shivang.s/anaconda/lib/python3.6/site-packages/psd_tools/api/layers.py", line 379, in compose
    return compose_layer(self, **kwargs)

  File "/Users/shivang.s/anaconda/lib/python3.6/site-packages/psd_tools/composer/__init__.py", line 163, in compose_layer
    return _apply_layer_ops(layer, image, force=force, **kwargs)

  File "/Users/shivang.s/anaconda/lib/python3.6/site-packages/psd_tools/composer/__init__.py", line 183, in _apply_layer_ops

  File "/Users/shivang.s/anaconda/lib/python3.6/site-packages/psd_tools/composer/__init__.py", line 283, in apply_mask
    )

AttributeError: 'Image' object has no attribute 'getchannel'

**Comment by change2014** [comment]
also i updated to recent version 1.8.29

**Comment by change2014** [comment]
here is the full code for your reference. 

from psd_tools import PSDImage 


psd = PSDImage.open('/Users/shivang.s/Documents/autoContent/DataSets/photoshopData/banner4/1312*704.psd')

k = 0 

for layer in psd:
    name = str(k)+".png"
    path = '/Users/shivang.s/Documents/autoContent/DataSets/photoshopData/banner3/elements/' + name
    img = layer.compose()
    if img:
        img.save(path)
    k = k +1

**Comment by kyamagu** [comment]
@change2014 What is your pillow version? Can you try upgrading pillow?

**Comment by change2014** [comment]
yes after upgrading it to recent pillow version its working fine. Thanks a lot for your help.
