### ISSUE TITLE
Can't open psd

### ISSUE THREAD

**Issue by MCVERTEX** [psd-tools/psd-tools#145]
I have this trace 

Traceback (most recent call last):
File "Z:\SOFTS\cgru\utilities\denoiser.py", line 92, in 
Denoise(argv)
File "Z:\SOFTS\cgru\utilities\denoiser.py", line 79, in Denoise
psd = PSDImage.open(os.path.dirname(RenderPath)+os.sep+file)
File "Z:\SOFTS\cgru\python\lib\site-packages\psd_tools\api\psd_image.py", line 106, in open
self = cls(PSD.read(f, **kwargs))
File "Z:\SOFTS\cgru\python\lib\site-packages\psd_tools\psd\__init__.py", line 72, in read
LayerAndMaskInformation.read(fp, encoding, header.version),
File "Z:\SOFTS\cgru\python\lib\site-packages\psd_tools\psd\layer_and_mask.py", line 58, in read
self = cls._read_body(fp, end_pos, encoding, version)
File "Z:\SOFTS\cgru\python\lib\site-packages\psd_tools\psd\layer_and_mask.py", line 65, in _read_body
layer_info = LayerInfo.read(fp, encoding, version)
File "Z:\SOFTS\cgru\python\lib\site-packages\psd_tools\psd\layer_and_mask.py", line 130, in read
self = cls._read_body(fp, encoding, version)
File "Z:\SOFTS\cgru\python\lib\site-packages\psd_tools\psd\layer_and_mask.py", line 139, in _read_body
layer_records = LayerRecords.read(fp, layer_count, encoding, version)
File "Z:\SOFTS\cgru\python\lib\site-packages\psd_tools\psd\layer_and_mask.py", line 337, in read
items.append(LayerRecord.read(fp, encoding, version))
File "Z:\SOFTS\cgru\python\lib\site-packages\psd_tools\psd\layer_and_mask.py", line 442, in read
*cls._read_extra(f, encoding, version)
File "Z:\SOFTS\cgru\python\lib\site-packages\psd_tools\psd\layer_and_mask.py", line 456, in _read_extra
tagged_blocks = TaggedBlocks.read(fp, version=version, padding=1)
File "Z:\SOFTS\cgru\python\lib\site-packages\psd_tools\psd\tagged_blocks.py", line 157, in read
block = TaggedBlock.read(fp, version, padding)
File "Z:\SOFTS\cgru\python\lib\site-packages\psd_tools\psd\tagged_blocks.py", line 252, in read
data = kls.frombytes(raw_data, version=version)
File "Z:\SOFTS\cgru\python\lib\site-packages\psd_tools\psd\base.py", line 65, in frombytes
return self.read(f, *args, **kwargs)
File "Z:\SOFTS\cgru\python\lib\site-packages\psd_tools\psd\base.py", line 370, in read
return cls(read_fmt('B3x', fp)[0])
File "Z:\SOFTS\cgru\python\lib\site-packages\psd_tools\utils.py", line 36, in read_fmt
) == fmt_size, 'read=%d, expected=%d' % (len(data), fmt_size)
AssertionError: read=2, expected=4

with this psd :
[test_AFrender_1_0001.zip](https://github.com/psd-tools/psd-tools/files/3631774/test_AFrender_1_0001.zip)

**Comment by kyamagu** [comment]
@MCVERTEX It seems the file is malformed, and is likely not generated by Adobe Photoshop. Nevertheless, v1.8.30 implements workaround for such files. Please upgrade.

**Comment by MCVERTEX** [comment]
it's a multipass file generated by C4D, i'll check that workaround thank you

**Comment by MCVERTEX** [comment]
it works, thanks again
