### ISSUE TITLE
Unable to open PSD file: AssertionError: read=1, expected=10

### ISSUE THREAD

**Issue by InkLabApp** [psd-tools/psd-tools#177]
**Environment**

* Python version: 3.6.9
* OS: Ubuntu 18.04 LTS

**Description**

Attempting to open the PSD file raises am immediate error. The file is able to be opened using the Krita painting app without notable issue. 

**Expected behavior**

Able to open a read basic information about layers in the PSD file using this API. (PSD file was provided by an artist after a commission, I did not manually create it)

**How to Reproduce**

1. Get package from '...'
pip3 install git+https://github.com/psd-tools/psd-tools
2. Then run '...'
`from psd_tools import PSDImage`
`psd = PSDImage.open('<path_to_the_file>.psd')`
3. An error occurs.

**Output**

```
Traceback (most recent call last):
  File "psd_to_ora.py", line 10, in <module>
    psd = PSDImage.open('<redacted>')
  File "/usr/local/lib/python3.6/dist-packages/psd_tools/api/psd_image.py", line 106, in open
    self = cls(PSD.read(f, **kwargs))
  File "/usr/local/lib/python3.6/dist-packages/psd_tools/psd/__init__.py", line 72, in read
    LayerAndMaskInformation.read(fp, encoding, header.version),
  File "/usr/local/lib/python3.6/dist-packages/psd_tools/psd/layer_and_mask.py", line 58, in read
    self = cls._read_body(fp, end_pos, encoding, version)
  File "/usr/local/lib/python3.6/dist-packages/psd_tools/psd/layer_and_mask.py", line 68, in _read_body
    global_layer_mask_info = GlobalLayerMaskInfo.read(fp)
  File "/usr/local/lib/python3.6/dist-packages/psd_tools/psd/layer_and_mask.py", line 938, in read
    return cls._read_body(f)
  File "/usr/local/lib/python3.6/dist-packages/psd_tools/psd/layer_and_mask.py", line 942, in _read_body
    overlay_color = list(read_fmt('5H', fp))
  File "/usr/local/lib/python3.6/dist-packages/psd_tools/utils.py", line 37, in read_fmt
    ) == fmt_size, 'read=%d, expected=%d' % (len(data), fmt_size)
AssertionError: read=1, expected=10
```
Attached the PSD file for testing: [PSD File.psd.zip](https://github.com/pypa/pip/files/4094855/PSD.File.psd.zip)

**Comment by kyamagu** [comment]
@InkLabApp This is very likely due to Krita app exporting a malformed PSD file. Specifically, [Global layer mask info section](https://www.adobe.com/devnet-apps/photoshop/fileformatashtml/#50577409_17115) is internally broken. I will add a bugfix to prevent a crash, but also recommend sending a bug report to Krita developers.

**Comment by InkLabApp** [comment]
@kyamagu Thank you for closing it so quickly! Just to clarify, I was able to open it with Krita, but I believe the original artist created the file with Apple "Procreate" software, which was what exported the PSD. I will see if I can forward the info to them!
