### ISSUE TITLE
1.9.8 composite layer bug

### ISSUE THREAD

**Issue by wushiwein119** [psd-tools/psd-tools#214]
An error occurred while I was exporting the laye
```
layer.composite().save('./preview.png')
[psd_8.psd.zip](https://github.com/psd-tools/psd-tools/files/4400656/psd_8.psd.zip)


```
```
Artboard('宝贝' size=288x477)
Traceback (most recent call last):
  File "index.py", line 62, in <module>
    opj = output2json('./psd_8.psd')
  File "index.py", line 43, in output2json
    dsl = Parse.export(trees[0])
  File "/Users/david.wsw/Documents/gitlab/mui/psd-parse-service/mods/parse.py", line 130, in export
    result.append(_export_mods(tree))
  File "/Users/david.wsw/Documents/gitlab/mui/psd-parse-service/mods/parse.py", line 34, in _export_mods
    layer.composite().save('./preview.png')
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/psd_tools/api/layers.py", line 677, in composite
    self, color, alpha, viewport, layer_filter, force, as_layer=True
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/psd_tools/composite/__init__.py", line 39, in composite_pil
    as_layer=as_layer
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/psd_tools/composite/__init__.py", line 108, in composite
    compositor.apply(layer)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/psd_tools/composite/__init__.py", line 190, in apply
    color, shape, alpha = self._get_group(layer, knockout)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/psd_tools/composite/__init__.py", line 287, in _get_group
    force=self._force
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/psd_tools/composite/__init__.py", line 108, in composite
    compositor.apply(layer)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/psd_tools/composite/__init__.py", line 190, in apply
    color, shape, alpha = self._get_group(layer, knockout)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/psd_tools/composite/__init__.py", line 287, in _get_group
    force=self._force
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/psd_tools/composite/__init__.py", line 108, in composite
    compositor.apply(layer)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/psd_tools/composite/__init__.py", line 190, in apply
    color, shape, alpha = self._get_group(layer, knockout)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/psd_tools/composite/__init__.py", line 287, in _get_group
    force=self._force
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/psd_tools/composite/__init__.py", line 108, in composite
    compositor.apply(layer)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/psd_tools/composite/__init__.py", line 212, in apply
    self._apply_stroke_effect(layer, color, shape_mask, alpha)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/psd_tools/composite/__init__.py", line 463, in _apply_stroke_effect
    self._viewport, shape, effect.value, layer._psd
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/psd_tools/composite/effects.py", line 38, in draw_stroke_effect
    edges = filters.scharr(shape[:, :, 0])
TypeError: 'float' object is not subscriptable
```
please help me

**Comment by wushiwein119** [comment]
[psd_8.psd.zip](https://github.com/psd-tools/psd-tools/files/4400658/psd_8.psd.zip)
