### ISSUE TITLE
Invalid layer in Procreate file

### ISSUE THREAD

**Issue by afrigon** [psd-tools/psd-tools#226]
**os**: MacOS 10.15.2
**version**: 1.9.12

When opening the procreate psd file I linked in this issue, I get the following crash.

```
global layer mask info is broken, expected 13 bytes but found only 1
Invalid signature (b'\x00\x00\x00\x01')

Traceback (most recent call last):
  File "./scripts/export.py", line 45, in <module>
    main(base_path)
  File "./scripts/export.py", line 11, in main
    generate_textures(base_path, Path("textures"))
  File "./scripts/export.py", line 24, in generate_textures
    generate_textures(base_path, directory)
  File "./scripts/export.py", line 28, in generate_textures
    psd = PSDImage.open(str(f))
  File "/usr/local/lib/python3.7/site-packages/psd_tools/api/psd_image.py", line 104, in open
    self = cls(PSD.read(f, **kwargs))
  File "/usr/local/lib/python3.7/site-packages/psd_tools/api/psd_image.py", line 43, in __init__
    self._init()
  File "/usr/local/lib/python3.7/site-packages/psd_tools/api/psd_image.py", line 595, in _init
    current_group._layers.append(layer)
UnboundLocalError: local variable 'layer' referenced before assignment
```

[cactus_top.psd.zip](https://github.com/psd-tools/psd-tools/files/4674660/cactus_top.psd.zip)

**Comment by kyamagu** [comment]
@afrigon Thanks for reporting this, will investigate
