### ISSUE TITLE
Low quality and color shift exporting CMYK psd to jpg/png

### ISSUE THREAD

**Issue by bvb-sc** [psd-tools/psd-tools#237]
Hi,

When executing the following command, a low quality and color shifted result is rendered: 

`psd-tools.exe export "cmyk.psd" "cmyk.jpg"` 

**Result**:

![image](https://user-images.githubusercontent.com/67702686/86270389-742bbc80-bbcb-11ea-8504-273d9a01b431.png)

**Expected result**:

![image](https://user-images.githubusercontent.com/67702686/86270419-80b01500-bbcb-11ea-8855-74de936d6723.png)

**Reference file**:

[cmyk.zip](https://github.com/psd-tools/psd-tools/files/4859213/cmyk.zip)

**Version info**:
OS: Windows
Python: 3.8.3
psd-tools: 1.9.13

**Additional info**:

Originally we wanted to export directly to png, but this resulted in the error below. The error makes sense, since png does not support CMYK and psd-tools doesn't seem to support native conversion from CMYK to PSD. Looking into PIL's Image & ImageCms features through scripting, we found color management methods, but they also result in a low quality and color shifted rendition.

```Traceback (most recent call last):
  File "XXX\python\python38\lib\site-packages\PIL\PngImagePlugin.py", line 1179, in _save
    rawmode, mode = _OUTMODES[mode]
KeyError: 'CMYK'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "XXX\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "XXX\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "XXX\Python\Python38\Scripts\psd-tools.exe\__main__.py", line 7, in <module>
  File "XXX\python\python38\lib\site-packages\psd_tools\__main__.py", line 58, in main
    image.save(args['<output_file>'])
  File "XXX\python\python38\lib\site-packages\PIL\Image.py", line 2134, in save
    save_handler(self, fp, filename)
  File "XXX\python\python38\lib\site-packages\PIL\PngImagePlugin.py", line 1181, in _save
    raise OSError("cannot write mode %s as PNG" % mode)
OSError: cannot write mode CMYK as PNG```

Any help on how to correctly convert psd to png, without color shifts/quality loss would be appreciated.

**Comment by kyamagu** [comment]
@bvb-sc Currently image export is via pillow. You might be able to get raw CMYK pixel arrays in numpy instead (`composite` function), and save in whatever format, but I suspect not many tools render CMYK image correctly in anyway. Alternatively, you can convert to RGB before saving to PNG or JPEG.

**Comment by bvb-sc** [comment]
Hi @kyamagu,

We've tried the conversion to RGB before saving to PNG or JPEG, but the output is the exact same: 
![cmyk_sample](https://user-images.githubusercontent.com/67702686/86345950-843fac80-bc5c-11ea-9ba6-b62856ea3466.png)

Sample code:

``` 
from psd_tools import PSDImage
from psd_tools.constants import Resource
from io import BytesIO
from PIL import Image
from PIL import ImageCms

# Open file
psd = PSDImage.open("cmyk.psd")

# ICC data
embedded_icc = psd.image_resources.get_data(Resource.ICC_PROFILE)
input_icc_profile = ImageCms.ImageCmsProfile(BytesIO(embedded_icc))
output_icc_profile = "AdobeRGB1998.icc"
output_icc_profile_file = open(output_icc_profile, "rb")
output_icc_profile_data = output_icc_profile_file.read()
output_icc_profile_file.close()

# Compose
composition = psd.composite()

# Color conversion
converted_composition = ImageCms.profileToProfile(composition, input_icc_profile, output_icc_profile, ImageCms.INTENT_PERCEPTUAL, "RGB")
#                                                                                                                                 ^ RGBA gives a fully transparent image, all other data is gone

# Save with embedded profile
converted_composition.save("<file>.png", format="PNG", icc_profile=output_icc_profile_data)

```

For files which have a preview, and where we use `psd.topil()` instead of `psd.composite()` we don't have unexpected output results.

**Comment by kyamagu** [comment]
Ok, will mark it as a bug. Likely pixel value representation issue

**Comment by Etienne-Gautier** [comment]
I know this is an old issue but I bumped into this as well and fixed it.
I found a post-processing step for CMYK in `psd.topil()` (see [this](https://github.com/psd-tools/psd-tools/blob/4ff198368eebcda7c8bf385a3129e7481fbae8ab/src/psd_tools/api/pil_io.py#L116) method) that wasn't replicated in `psd.composite()`

If you add the following code after the call to `psd.composite()` you will get the expected result:

```
        if image.mode == 'CMYK':
            from PIL import ImageChops
            image = ImageChops.invert(image)
```


@kyamagu, should this step be part of `layer.composite()`?

**Comment by kyamagu** [comment]
@Etienne-Gautier 
> should this step be part of layer.composite()?

Likely. The current implementation of `composite` is different from `topil`, but should be able to merge certain steps. The complication is that, psd-tools does not yet support blending in CMYK and generally `composite` fails except when there is a pre-composited pixels in the PSD file. This post-processing should happen only when there is a pre-composited pixels.
