### ISSUE TITLE
Memory Consumption

### ISSUE THREAD

**Issue by bvb-sc** [psd-tools/psd-tools#244]
**Question**
When compositing large psd/psb files, RAM memory consumption is very high. E.g. a 600MB psd file takes up to 16GB RAM memory.

Is there a way to limit the amount of memory used?

**Environment**
 - Python [3.8.2]
 - Version [v1.9.13]

**Comment by kyamagu** [comment]
One approach in Linux is to set process memory limit. Otherwise, the current numpy-based implementation cannot avoid memory use.

```python
from resource import RLIMIT_AS, getrlimit, setrlimit

def memory_limit(limit=1024**3):
    soft, hard = getrlimit(RLIMIT_AS)
    setrlimit(RLIMIT_AS, (limit, hard))
```

**Comment by bvb-sc** [comment]
Hi,

Using provided snippet, we seems to be getting the following error:

`$ script /tmp/file.psd /tmp/file.png
Loading file: /tmp/file.psd
Traceback (most recent call last):
  File "/usr/bin/script", line 71, in <module>
    Convert(sys.argv[1], sys.argv[2])
  File "/usr/bin/script", line 28, in Convert
    psd = PSDImage.open(input)
  File "/usr/local/lib/python3.7/dist-packages/psd_tools/api/psd_image.py", line 104, in open
    self = cls(PSD.read(f, **kwargs))
  File "/usr/local/lib/python3.7/dist-packages/psd_tools/psd/__init__.py", line 72, in read
    LayerAndMaskInformation.read(fp, encoding, header.version),
  File "/usr/local/lib/python3.7/dist-packages/psd_tools/psd/layer_and_mask.py", line 58, in read
    self = cls._read_body(fp, end_pos, encoding, version)
  File "/usr/local/lib/python3.7/dist-packages/psd_tools/psd/layer_and_mask.py", line 75, in _read_body
    fp, version=version, padding=4, end_pos=end_pos
  File "/usr/local/lib/python3.7/dist-packages/psd_tools/psd/tagged_blocks.py", line 158, in read
    block = TaggedBlock.read(fp, version, padding)
  File "/usr/local/lib/python3.7/dist-packages/psd_tools/psd/tagged_blocks.py", line 256, in read
    data = kls.frombytes(raw_data, version=version)
  File "/usr/local/lib/python3.7/dist-packages/psd_tools/psd/base.py", line 68, in frombytes
    return self.read(f, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/psd_tools/psd/layer_and_mask.py", line 189, in read
    return cls._read_body(fp, encoding, version)
  File "/usr/local/lib/python3.7/dist-packages/psd_tools/psd/layer_and_mask.py", line 142, in _read_body
    channel_image_data = ChannelImageData.read(fp, layer_records)
  File "/usr/local/lib/python3.7/dist-packages/psd_tools/psd/layer_and_mask.py", line 794, in read
    items.append(ChannelDataList.read(fp, layer.channel_info))
  File "/usr/local/lib/python3.7/dist-packages/psd_tools/psd/layer_and_mask.py", line 826, in read
    items.append(ChannelData.read(fp, c.length - 2, **kwargs))
  File "/usr/local/lib/python3.7/dist-packages/psd_tools/psd/layer_and_mask.py", line 858, in read
    data = fp.read(length)
MemoryError`

Is it safe to assume that limiting the process memory, simply stops the process when the memory limit is reached?
For example, limiting the process memory to 1GB still makes it impossible to process aforementioned file that would normally require 16GB RAM memory?

**Comment by kyamagu** [comment]
Yep, this is a safeguard against system. Does not mean psd-tools reduces the memory usage.
