### ISSUE TITLE
question: can't export 16bit png file

### ISSUE THREAD

**Issue by jeremybep** [psd-tools/psd-tools#250]
Hi, 
I've got some trouble to export 16bit png from 16bit PSD:
What i try to do :

`
from psd_tools import PSDImage

psd = PSDImage.open(sel_local_psd_file)
bbox = (0, 0, abs(psd.size[0]), abs(psd.size[1]))

for layer in psd:
    if layer.is_group() and layer.is_visible():
        layer_image = layer.composite(viewport=bbox)
        layerName = os.path.join(local_png_folder, layer.name.upper() + "-1.png")
        lyr_16bit = layerName.topil()
        lyr_16bit.convert("PA", colors = 256)
        layer_image.save(lyr_16bit)
`
i've got NoneType object ? what i'm missing ?
regards,

**Comment by jeremybep** [comment]
ok, its a begining : 

```python

from psd_tools import PSDImage

psd = PSDImage.open(sel_local_psd_file)
bbox = (0, 0, abs(psd.size[0]), abs(psd.size[1]))

for layer in psd:
    if layer.is_group() and layer.is_visible():
        layer_image = layer.composite(viewport=bbox)
        lyr_16bit = layer_image.convert("I;16")
        lyr_full_path = os.path.join(local_png_folder, layer.name.upper() + "-1.png")
        lyr_16bit.save(lyr_full_path)

```

Error >>

```
Traceback (most recent call last):
  File "C:\Users\user\Documents\TEST_PY\test_sanity.py", line 18, in <module>
    lyr_16bit = layer_image.convert("I;16")
  File "C:\Users\user\AppData\Roaming\Python\Python37\site-packages\PIL\Image.py", line 1029, in convert
    im = im.convert(mode, dither)
ValueError: conversion from RGB to I;16 not supported
```

**Comment by jeremybep** [comment]
Ok, i've found a way...
``` python
from psd_tools import PSDImage
import numpy as np
from numpngw import write_png
psd = PSDImage.open(psd_file)
# get viewport bbox of psd file
bbox = (0, 0, abs(psd.size[0]), abs(psd.size[1]))
for layer in psd:
    if layer.is_group() and layer.is_visible():
        # composite return PIL.image
        layer_image = layer.composite(viewport=bbox)
        # now we can convert PIL.image to numpy array
        img = np.array(layer_image, dtype=np.uint8)
        # table to 16 bit int
        img16 = (65535*((img - img.min())/img.ptp())).astype(np.uint16)
        lyr_full_path = os.path.join(folder, layer.name, ".png")
        # force saving with numpngw
        write_png(lyr_full_path, img16, bitdepth=16)

```
Composite() via psd-tool flattens the level on 8Bit even with a psd in 16bit

**Comment by kotyache** [comment]
@jeremybep  Was a great starting point but some images get darker tones on export, I ended up using 

`
    image = layer.composite()
    imgArr16 = (np.array(image) / 255 * 65535).astype(np.uint16) 
    write_png(savePath, imgArr16, iccp=iccprofile)
`

The only issue is  layer.composite() stripping off 16 bit data. Psd-tools support 32-bit, would be better to composite in 32 and convert to 16 bit, but I cannot find any information on wether it is possible or how to do it -- would appreciate any information on this

**Comment by kotyache** [comment]
figured out how to avoid losing 16 bit color data. This is based on @kyamagu's [answer](https://github.com/psd-tools/psd-tools/issues/202#issuecomment-597955164) about obtaining composite data

```python

import numpy as np
from numpngw import write_png
from psd_tools import PSDImage
from psd_tools.composite import composite

psd = PSDImage.open(psdPath)
color, shape, alpha = composite(psd)
rgba = np.concatenate((color, alpha), axis=2)
imgArr16 = (rgba * 65535).astype(np.uint16) 
write_png(savePath, imgArr16)

```
