### ISSUE TITLE
File Not Found in layer data

### ISSUE THREAD

**Issue by wdagung** [psd-tools/psd-tools#263]
Hi,
The PSD object return FileNotFoundError when trying to access smart object layer data

**To Reproduce**
```python
from psd_tools import PSDImage
psd = PSDImage.open('B37_Movie frame 04 hi.psd')
psd._layers[2].smart_object.data
```

**Environment**
- MacOS 11.2.2
 - Python [3.8]
 - Version [v1.9.17]

**Additional context**

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/user/opt/anaconda3/lib/python3.8/site-packages/psd_tools/api/smart_object.py", line 90, in data
    with self.open() as f:
  File "/Users/user/opt/anaconda3/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/Users/user/opt/anaconda3/lib/python3.8/site-packages/psd_tools/api/smart_object.py", line 79, in open
    with open(filepath, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '../../in game screenshot/in game screenshot/WhatsApp Image 2020-07-14 at 12.21.14 PM (2).jpeg'
```

**Comment by kyamagu** [comment]
This literally indicates the file is not found. Probably the file is not embedded but only linked in the PSD creator's environment. Open the file in Photoshop and see if the file is embedded.
