### ISSUE TITLE
Encountered an error while opening a large PSD file.

### ISSUE THREAD

**Issue by Tunanzzz** [psd-tools/psd-tools#398]
**Describe the bug**
Opening PSD files smaller than 50MB works fine, but encountering errors when opening PSD files larger than 50MB.

```python
psd_file = "/home/zhoupc/template-photoshop/data/fo/subheading/14.psd"
psd_file = PSDImage.open(psd_file)
print(len(psd_file._layers))
```

**Environment**
 - Python [3.11]
 - Version [v1.9.31]

**Comment by Tunanzzz** [comment]
The PSD file is confirmed to be intact and can be opened successfully using Photoshop.

**Comment by Tunanzzz** [comment]
bug detail：
Traceback (most recent call last):
  File "/home/zhoupc/template-photoshop/zhoupc-test/test.py", line 12, in <module>
    psd_file = PSDImage.open(psd_file)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda/lib/python3.11/site-packages/psd_tools/api/psd_image.py", line 116, in open
    self = cls(PSD.read(f, **kwargs))
               ^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda/lib/python3.11/site-packages/psd_tools/psd/__init__.py", line 76, in read
    LayerAndMaskInformation.read(fp, encoding, header.version),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda/lib/python3.11/site-packages/psd_tools/psd/layer_and_mask.py", line 71, in read
    self = cls._read_body(fp, end_pos, encoding, version)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda/lib/python3.11/site-packages/psd_tools/psd/layer_and_mask.py", line 82, in _read_body
    layer_info = LayerInfo.read(fp, encoding, version)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda/lib/python3.11/site-packages/psd_tools/psd/layer_and_mask.py", line 149, in read
    self = cls._read_body(fp, encoding, version)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda/lib/python3.11/site-packages/psd_tools/psd/layer_and_mask.py", line 160, in _read_body
    channel_image_data = ChannelImageData.read(fp, layer_records)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda/lib/python3.11/site-packages/psd_tools/psd/layer_and_mask.py", line 864, in read
    items.append(ChannelDataList.read(fp, layer.channel_info))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda/lib/python3.11/site-packages/psd_tools/psd/layer_and_mask.py", line 891, in read
    items.append(ChannelData.read(fp, c.length - 2, **kwargs))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda/lib/python3.11/site-packages/psd_tools/psd/layer_and_mask.py", line 921, in read
    compression = Compression(read_fmt("H", fp)[0])
                              ^^^^^^^^^^^^^^^^^
  File "/root/anaconda/lib/python3.11/site-packages/psd_tools/utils.py", line 37, in read_fmt
    assert len(data) == fmt_size, "read=%d, expected=%d" % (len(data), fmt_size)
           ^^^^^^^^^^^^^^^^^^^^^
AssertionError: read=0, expected=2
