### ISSUE TITLE
Error loading psd file created by Clip Studio Paint

### ISSUE THREAD

**Issue by davisan** [psd-tools/psd-tools#47]
Hello! I can't open a PSD file created by Clip Studio Paint with psd-tools, though I can open it in Photoshop without problems. What can be?
Thank you!

PSD file:
https://dl.dropboxusercontent.com/u/36540898/teste2.psd

Code:
from psd_tools import PSDImage
from PIL import Image
import os
import sys
from os.path import basename
psdRoot = '.'
psdFiles = []
for root, dir, files in os.walk(psdRoot):
    for thisFile in files:
        if (thisFile.lower().endswith('.psd')):
            fullFilename = os.path.join(root, thisFile)
            psdFiles.append(os.path.dirname(os.path.realpath(fullFilename)) + '\' + thisFile)
for psdFile in psdFiles:
   psd = PSDImage.load(psdFile)

Traceback (most recent call last):
  File "C:/Projetos/DPEngine/DavisanUtils/ExportGroups/test.py", line 17, in <module>
    psd = PSDImage.load(psdFile)
  File "C:\Python27\lib\site-packages\psd_tools\user_api\psd_image.py", line 239, in load
    return cls.from_stream(fp, encoding)
  File "C:\Python27\lib\site-packages\psd_tools\user_api\psd_image.py", line 247, in from_stream
    psd_tools.reader.parse(fp, encoding)
  File "C:\Python27\lib\site-packages\psd_tools\decoder\decoder.py", line 32, in parse
    image_resource_blocks = image_resources.decode(reader_parse_result.image_resource_blocks),
  File "C:\Python27\lib\site-packages\psd_tools\decoder\image_resources.py", line 60, in decode
    return [parse_image_resource(res) for res in image_resource_blocks]
  File "C:\Python27\lib\site-packages\psd_tools\decoder\image_resources.py", line 70, in parse_image_resource
    return resource._replace(data = decoder(resource.data))
  File "C:\Python27\lib\site-packages\psd_tools\decoder\decoders.py", line 14, in unicode_string
    return read_unicode_string(io.BytesIO(data))
  File "C:\Python27\lib\site-packages\psd_tools\utils.py", line 45, in read_unicode_string
    num_chars = read_fmt("I", fp)[0]
  File "C:\Python27\lib\site-packages\psd_tools\utils.py", line 24, in read_fmt
    assert len(data) == fmt_size, (len(data), fmt_size)
AssertionError: (0, 4)

**Comment by EvgenKo423** [comment]
Hi, @davisan.

There is a problem with decoder. There are some PSD files which contain data blocks with zero-length data. When decoder tries to handle them, it fails.

Thanks for the report, it will be fixed in a next release.

**Comment by alexionne** [comment]
Hi!
Just wanted to bump this thread - I hit same problem today.
Thanks!

File: [test.zip](https://github.com/psd-tools/psd-tools/files/702397/test.zip)

Python 3.5.1 (default, Jan  1 2016, 20:37:59) [MSC v.1900 64 bit (AMD64)] on win32

Traceback (most recent call last):
  File "mhg_export_psd.py", line 33, in <module>
    export_psd_file("../../data/test/_test.mscene")
  File "mhg_export_psd.py", line 13, in export_psd_file
    psd = psd_tools.PSDImage.load(psd_filename)
  File "P:\tools\mblender\2.78\python\lib\site-packages\psd_tools\user_api\psd_image.py", line 239, in load
    return cls.from_stream(fp, encoding)
  File "P:\tools\mblender\2.78\python\lib\site-packages\psd_tools\user_api\psd_image.py", line 247, in from_stream
    psd_tools.reader.parse(fp, encoding)
  File "P:\tools\mblender\2.78\python\lib\site-packages\psd_tools\decoder\decoder.py", line 10, in parse
    image_resource_blocks = image_resources.decode(image_resource_blocks)
  File "P:\tools\mblender\2.78\python\lib\site-packages\psd_tools\decoder\image_resources.py", line 60, in decode
    return [parse_image_resource(res) for res in image_resource_blocks]
  File "P:\tools\mblender\2.78\python\lib\site-packages\psd_tools\decoder\image_resources.py", line 60, in <listcomp>
    return [parse_image_resource(res) for res in image_resource_blocks]
  File "P:\tools\mblender\2.78\python\lib\site-packages\psd_tools\decoder\image_resources.py", line 70, in parse_image_resource
    return resource._replace(data = decoder(resource.data))
  File "P:\tools\mblender\2.78\python\lib\site-packages\psd_tools\decoder\decoders.py", line 14, in unicode_string
    return read_unicode_string(io.BytesIO(data))
  File "P:\tools\mblender\2.78\python\lib\site-packages\psd_tools\utils.py", line 45, in read_unicode_string
    num_chars = read_fmt("I", fp)[0]
  File "P:\tools\mblender\2.78\python\lib\site-packages\psd_tools\utils.py", line 24, in read_fmt
    assert len(data) == fmt_size, (len(data), fmt_size)
AssertionError: (0, 4)

**Comment by alexionne** [comment]
Hi again,

Here's patch that solves this particular crash. It assumes that all default types are serialized as series of 0's.

[psd_tools_zero_data_fix.zip](https://github.com/psd-tools/psd-tools/files/702521/psd_tools_zero_data_fix.zip)
