### ISSUE TITLE
PSD. Load failes in Ubuntu 14.04 for Specific File but works in Mac

### ISSUE THREAD

**Issue by ramitwadhwa** [psd-tools/psd-tools#57]
Error Log:

Traceback (most recent call last):
  File "test_psd-tool.py", line 8, in <module>
    img = PSDImage.load(filename)
  File "/usr/local/lib/python2.7/dist-packages/psd_tools/user_api/psd_image.py", line 239, in load
    return cls.from_stream(fp, encoding)
  File "/usr/local/lib/python2.7/dist-packages/psd_tools/user_api/psd_image.py", line 247, in from_stream
    psd_tools.reader.parse(fp, encoding)
  File "/usr/local/lib/python2.7/dist-packages/psd_tools/decoder/decoder.py", line 32, in parse
    image_resource_blocks = image_resources.decode(reader_parse_result.image_resource_blocks),
  File "/usr/local/lib/python2.7/dist-packages/psd_tools/decoder/image_resources.py", line 60, in decode
    return [parse_image_resource(res) for res in image_resource_blocks]
  File "/usr/local/lib/python2.7/dist-packages/psd_tools/decoder/image_resources.py", line 70, in parse_image_resource
    return resource._replace(data = decoder(resource.data))
  File "/usr/local/lib/python2.7/dist-packages/psd_tools/decoder/image_resources.py", line 143, in _decode_icc
    return ImageCms.ImageCmsProfile(io.BytesIO(data))
  File "/usr/local/lib/python2.7/dist-packages/PIL/ImageCms.py", line 164, in __init__
    self._set(core.profile_frombytes(profile.read()))
  File "/usr/local/lib/python2.7/dist-packages/PIL/_util.py", line 27, in __getattr__
    raise self.ex
ImportError: cannot import name _imagingcms

Little-CMS2 is installed and Pillow & PSD_Tools were uninstalled and re-installd multiple times.

This file has Color Profile: sRGB IEC61966-2.1

It works on Mac but does not work on Ubuntu.

**Comment by kyamagu** [comment]
Install littleCML
