### ISSUE TITLE
MemoryError when loading a very large psd

### ISSUE THREAD

**Issue by kidsang** [psd-tools/psd-tools#58]
I have an very large psd file (about 1.17GB). When I load this psd file use PSDImage.load(), I got a memory error. The trace back is like:

Traceback (most recent call last):
  File "C:\mypath\testpsd.py", line 3, in <module>
    psd = PSDImage.load("test.psd")
  File "C:\Python27\lib\site-packages\psd_tools\user_api\psd_image.py", line 239, in load
    return cls.from_stream(fp, encoding)
  File "C:\Python27\lib\site-packages\psd_tools\user_api\psd_image.py", line 247, in from_stream
    psd_tools.reader.parse(fp, encoding)
  File "C:\Python27\lib\site-packages\psd_tools\decoder\decoder.py", line 14, in parse
    new_tagged_blocks = tagged_blocks.decode(layer_and_mask_data.tagged_blocks)
  File "C:\Python27\lib\site-packages\psd_tools\decoder\tagged_blocks.py", line 47, in decode
    return [parse_tagged_block(block) for block in tagged_blocks]
  File "C:\Python27\lib\site-packages\psd_tools\decoder\tagged_blocks.py", line 59, in parse_tagged_block
    return Block(block.key, decoder(block.data))
  File "C:\Python27\lib\site-packages\psd_tools\decoder\tagged_blocks.py", line 239, in _decode_linked_layer
    return decode(data)
  File "C:\Python27\lib\site-packages\psd_tools\decoder\linked_layer.py", line 47, in decode
    fp = io.BytesIO(data)
MemoryError

**Comment by kyamagu** [comment]
Related: https://github.com/kyamagu/psd-tools/issues/76

**Comment by zewt** [comment]
I'm having this problem, too.  I'm using psd-tools to extract layer info, and it's running out of memory, even though I don't need image data at all.  I've worked around it by making ChannelDataList.read seek past image data without reading it.  There should be an option to not load image bitmap data, since it's often not needed and it's probably the massive bulk of memory usage in most cases.

**Comment by kyamagu** [comment]
@zewt Lazy loading might be possible, though this makes writing support complicated. In any case, Windows seem a bad platform.

**Comment by zewt** [comment]
I guess (blame Cygwin if anything).  Getting writing support working is much more important than lazy loading, but just having a way to make it skip images when you don't need bitmap data would be helpful.  Even when memory isn't a problem, it makes opening a large PSD go from 5.5 seconds to 1.6 for me, which is a huge difference when the rest of the script takes less than a second.

It doesn't seem like the code is structured to pass options down to the low-level readers.  I guess it would also want a way to flag a ListElement so that any attempts to access it throw an exception, so that any attempts to access image data fail predictably.

**Comment by kyamagu** [comment]
@zewt Thanks for the suggestion. The current design does not keep a file pointer after open, and that makes it difficult to implement lazy loading. As you suggest, metadata-only mode might be possible as an alternative. That will disable any access to pixels, but is easier to implement.

**Comment by kyamagu** [comment]
Peak memory usage is reduced in 1.8.11 (#99). Metadata-only approach is still ongoing.

**Comment by Constuelo** [comment]
metadata only would be useful
