### ISSUE TITLE
Invalid Resource Signature

### ISSUE THREAD

**Issue by Zaldor** [psd-tools/psd-tools#70]
Trying to read a file created from Adobe Photoshop CS6 on Windows 10 , any idea?

```
Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from psd_tools import PSDImage
>>> psd = PSDImage.load('D:\myFile.psd')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\python27\lib\site-packages\psd_tools\user_api\psd_image.py", line 239, in load
    return cls.from_stream(fp, encoding)
  File "c:\python27\lib\site-packages\psd_tools\user_api\psd_image.py", line 247, in from_stream
    psd_tools.reader.parse(fp, encoding)
  File "c:\python27\lib\site-packages\psd_tools\reader\reader.py", line 24, in parse
    psd_tools.reader.image_resources.read(fp, encoding),
  File "c:\python27\lib\site-packages\psd_tools\reader\image_resources.py", line 32, in read
    block = _read_block(fp, encoding)
  File "c:\python27\lib\site-packages\psd_tools\reader\image_resources.py", line 45, in _read_block
    raise Error("Invalid resource signature (%r)" % sig)
psd_tools.exceptions.Error: Invalid resource signature ('\x00\x00\x00\x00')
>>>
```

**Comment by kyamagu** [comment]
Likely fixed #91
