### ISSUE TITLE
Error in layer.as_PIL()

### ISSUE THREAD

**Issue by Fmijsters** [psd-tools/psd-tools#79]
I'm trying to export a layer as an image but i keep getting this error:

Traceback (most recent call last):
  File "C:\Users\fmijs\Desktop\Bizzerdloader\bizzerdloader.py", line 121, in <module>
    layer_image = layer.as_PIL()
  File "C:\Python34\lib\site-packages\psd_tools\user_api\psd_image.py", line 103, in as_PIL
    return self._psd._layer_as_PIL(self._index)
  File "C:\Python34\lib\site-packages\psd_tools\user_api\psd_image.py", line 288, in _layer_as_PIL
    return pil_support.extract_layer_image(self.decoded_data, index)
  File "C:\Python34\lib\site-packages\psd_tools\user_api\pil_support.py", line 45, in extract_layer_image
    icc_profile = get_icc_profile(decoded_data)
  File "C:\Python34\lib\site-packages\psd_tools\user_api\pil_support.py", line 114, in _channel_data_to_PIL
    depth=depth
  File "C:\Python34\lib\site-packages\psd_tools\user_api\pil_support.py", line 180, in _get_band_images
    im = frombytes('L', size, channel.data, "packbits", 'L')
NameError: name 'frombytes' is not defined

I updated to the last version of psd-tools also tried reinstalling but wont fix it.

Thanks in advance

**Comment by kyamagu** [comment]
Fixed #91
