### ISSUE TITLE
error: TypeError: namedtuple() got an unexpected keyword argument 'verbose' what can I do?

### ISSUE THREAD

**Issue by neemxyang** [psd-tools/psd-tools#86]
Traceback (most recent call last):
  File "D:\psd.py", line 1, in <module>
    import psd_tools
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\psd_tools\__init__.py", line 2, in <module>
    from .user_api import PSDImage, Layer, Group, BBox, Embedded
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\psd_tools\user_api\__init__.py", line 4, in <module>
    from psd_tools.user_api.psd_image import PSDImage, Layer, Group, BBox
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\psd_tools\user_api\psd_image.py", line 7, in <module>
    import psd_tools.reader
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\psd_tools\reader\__init__.py", line 3, in <module>
    from .reader import parse
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\psd_tools\reader\reader.py", line 8, in <module>
    import psd_tools.reader.layers
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\psd_tools\reader\layers.py", line 17, in <module>
    LayerAndMaskData = pretty_namedtuple('LayerAndMaskData', 'layers global_mask_info tagged_blocks')
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\psd_tools\debug.py", line 39, in pretty_namedtuple
    cls = namedtuple(typename, field_names, verbose=verbose)
TypeError: namedtuple() got an unexpected keyword argument 'verbose'
what can I do?

**Comment by neemxyang** [comment]
the origial py file as follow:
d:\psd.py
import psd_tools
psd = psd_tools.PSDImage.load('d:\\1.psd')
psd.header

**Comment by M-gen** [comment]
By installing another version, we were able to output and save the file
It seems that you can not just install psd-tools
X: pip install psd-tools
O: pip install psd-tools3

**Comment by kyamagu** [comment]
Fixed #90
