### ISSUE TITLE
AssertionError loading PSB

### ISSUE THREAD

**Issue by felipeprov** [psd-tools/psd-tools#95]
Hi

I am having an assertion error when reading my PSB files. 
I am attaching the file here.

It is very weird because I use the same version the artist, but I see no error with the files created by me...

[HUD.zip](https://github.com/psd-tools/psd-tools/files/2907075/HUD.zip)
PSDImage.open('samples\MAIN\HUD.psb')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python37\lib\site-packages\psd_tools\api\psd_image.py", line 101, in open
    self = cls(PSD.read(f))
  File "C:\Python37\lib\site-packages\psd_tools\psd\__init__.py", line 72, in read
    LayerAndMaskInformation.read(fp, encoding, header.version),
  File "C:\Python37\lib\site-packages\psd_tools\psd\layer_and_mask.py", line 57, in read
    return cls._read_body(f, encoding, version)
  File "C:\Python37\lib\site-packages\psd_tools\psd\layer_and_mask.py", line 69, in _read_body
    tagged_blocks = TaggedBlocks.read(fp, version=version, padding=4)
  File "C:\Python37\lib\site-packages\psd_tools\psd\tagged_blocks.py", line 151, in read
    block = TaggedBlock.read(fp, version, padding)
  File "C:\Python37\lib\site-packages\psd_tools\psd\tagged_blocks.py", line 240, in read
    data = kls.frombytes(raw_data, version=version)
  File "C:\Python37\lib\site-packages\psd_tools\psd\base.py", line 65, in frombytes
    return self.read(f, *args, **kwargs)
  File "C:\Python37\lib\site-packages\psd_tools\psd\descriptor.py", line 723, in read
    version = read_fmt('I', fp)[0]
  File "C:\Python37\lib\site-packages\psd_tools\utils.py", line 36, in read_fmt
    len(data), fmt_size
AssertionError: read=0, expected=4

**Comment by kyamagu** [comment]
@felipeprov thanks for a report, fixed in the latest release
